<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['id' => 1, 'province_id' => 1, 'city' => 'East London'],
            ['id' => 2, 'province_id' => 1, 'city' => 'Port Elizabeth'],
            ['id' => 3, 'province_id' => 1, 'city' => 'Bhisho'],
            ['id' => 4, 'province_id' => 1, 'city' => 'Umtata'],
            ['id' => 5, 'province_id' => 1, 'city' => 'Queenstown'],
            ['id' => 6, 'province_id' => 1, 'city' => 'Uitenhage'],
            ['id' => 7, 'province_id' => 1, 'city' => 'Grahamstown'],
            ['id' => 8, 'province_id' => 1, 'city' => 'Aliwal North'],
            ['id' => 9, 'province_id' => 1, 'city' => 'Cradock'],
            ['id' => 10, 'province_id' => 1, 'city' => 'Jeffrey’s Bay'],
            ['id' => 11, 'province_id' => 1, 'city' => 'Summerstrand'],
            ['id' => 12, 'province_id' => 1, 'city' => 'Lorraine'],
            ['id' => 13, 'province_id' => 1, 'city' => 'Breidbach'],
            ['id' => 14, 'province_id' => 1, 'city' => 'Kenton on Sea'],
            ['id' => 15, 'province_id' => 1, 'city' => 'Bluewater Bay'],
            ['id' => 16, 'province_id' => 2, 'city' => 'Welkom'],
            ['id' => 17, 'province_id' => 2, 'city' => 'Bloemfontein'],
            ['id' => 18, 'province_id' => 2, 'city' => 'Sasolburg'],
            ['id' => 19, 'province_id' => 2, 'city' => 'Kroonstad'],
            ['id' => 20, 'province_id' => 2, 'city' => 'Odendaalsrus'],
            ['id' => 21, 'province_id' => 2, 'city' => 'Frankfort'],
            ['id' => 22, 'province_id' => 3, 'city' => 'Johannesburg'],
            ['id' => 23, 'province_id' => 3, 'city' => 'Soweto'],
            ['id' => 24, 'province_id' => 3, 'city' => 'Vereeniging'],
            ['id' => 25, 'province_id' => 3, 'city' => 'Pretoria'],
            ['id' => 26, 'province_id' => 3, 'city' => 'Katlehong'],
            ['id' => 27, 'province_id' => 3, 'city' => 'Randburg'],
            ['id' => 28, 'province_id' => 3, 'city' => 'Roodepoort'],
            ['id' => 29, 'province_id' => 3, 'city' => 'Boksburg'],
            ['id' => 30, 'province_id' => 3, 'city' => 'Germiston'],
            ['id' => 31, 'province_id' => 3, 'city' => 'Centurion'],
            ['id' => 32, 'province_id' => 3, 'city' => 'Springs'],
            ['id' => 33, 'province_id' => 3, 'city' => 'Sandton'],
            ['id' => 34, 'province_id' => 3, 'city' => 'Benoni'],
            ['id' => 35, 'province_id' => 3, 'city' => 'Krugersdorp'],
            ['id' => 36, 'province_id' => 3, 'city' => 'Alberton'],
            ['id' => 37, 'province_id' => 3, 'city' => 'Edenvale'],
            ['id' => 38, 'province_id' => 3, 'city' => 'Bronkhorstspruit'],
            ['id' => 39, 'province_id' => 3, 'city' => 'Primrose'],
            ['id' => 40, 'province_id' => 3, 'city' => 'Bedfordview'],
            ['id' => 41, 'province_id' => 3, 'city' => 'Elsburg'],
            ['id' => 42, 'province_id' => 4, 'city' => 'Pietermaritzburg'],
            ['id' => 43, 'province_id' => 4, 'city' => 'Durban'],
            ['id' => 44, 'province_id' => 4, 'city' => 'Newcastle'],
            ['id' => 45, 'province_id' => 4, 'city' => 'Vryheid'],
            ['id' => 46, 'province_id' => 4, 'city' => 'Westville'],
            ['id' => 47, 'province_id' => 4, 'city' => 'Ulundi'],
            ['id' => 48, 'province_id' => 4, 'city' => 'New Hanover'],
            ['id' => 49, 'province_id' => 5, 'city' => 'Polokwane'],
            ['id' => 50, 'province_id' => 5, 'city' => 'Thohoyandou'],
            ['id' => 51, 'province_id' => 5, 'city' => 'Ga-Kgapane'],
            ['id' => 52, 'province_id' => 6, 'city' => 'Middelburg'],
            ['id' => 53, 'province_id' => 6, 'city' => 'Witbank'],
            ['id' => 54, 'province_id' => 6, 'city' => 'Bethal'],
            ['id' => 55, 'province_id' => 6, 'city' => 'Lydenburg'],
            ['id' => 56, 'province_id' => 6, 'city' => 'Breyten'],
            ['id' => 57, 'province_id' => 6, 'city' => 'Chrissiesmeer'],
            ['id' => 58, 'province_id' => 6, 'city' => 'Nelspruit'],
            ['id' => 59, 'province_id' => 7, 'city' => 'Rustenburg'],
            ['id' => 60, 'province_id' => 7, 'city' => 'Klerksdorp'],
            ['id' => 61, 'province_id' => 7, 'city' => 'Potchefstroom'],
            ['id' => 62, 'province_id' => 7, 'city' => 'Brits'],
            ['id' => 63, 'province_id' => 7, 'city' => 'Mmabatho'],
            ['id' => 64, 'province_id' => 7, 'city' => 'Mahikeng'],
            ['id' => 65, 'province_id' => 8, 'city' => 'Kimberley'],
            ['id' => 66, 'province_id' => 8, 'city' => 'Upington'],
            ['id' => 67, 'province_id' => 8, 'city' => 'Prieska'],
            ['id' => 68, 'province_id' => 8, 'city' => 'Kuruman'],
            ['id' => 69, 'province_id' => 8, 'city' => 'Carnarvon'],
            ['id' => 70, 'province_id' => 9, 'city' => 'Cape Town'],
            ['id' => 71, 'province_id' => 9, 'city' => 'Khayelitsha'],
            ['id' => 72, 'province_id' => 9, 'city' => 'Mitchells Plain'],
            ['id' => 73, 'province_id' => 9, 'city' => 'George'],
            ['id' => 74, 'province_id' => 9, 'city' => 'Paarl'],
            ['id' => 75, 'province_id' => 9, 'city' => 'Worcester'],
            ['id' => 76, 'province_id' => 9, 'city' => 'Saldanha'],
            ['id' => 77, 'province_id' => 9, 'city' => 'Oudtshoorn'],
            ['id' => 78, 'province_id' => 9, 'city' => 'Mossel Bay'],
            ['id' => 79, 'province_id' => 9, 'city' => 'Kuilsrivier'],
            ['id' => 80, 'province_id' => 9, 'city' => 'Beaufort West'],
            ['id' => 81, 'province_id' => 9, 'city' => 'Vredenburg'],
            ['id' => 82, 'province_id' => 9, 'city' => 'Malmesbury'],
            ['id' => 83, 'province_id' => 9, 'city' => 'Stellenbosch'],
            ['id' => 84, 'province_id' => 9, 'city' => 'Montagu'],
            ['id' => 85, 'province_id' => 9, 'city' => 'Bredasdorp'],
            ['id' => 86, 'province_id' => 9, 'city' => 'Velddrif'],
            ['id' => 87, 'province_id' => 9, 'city' => 'Saron'],
            ['id' => 88, 'province_id' => 9, 'city' => 'Citrusdal'],
            ['id' => 89, 'province_id' => 9, 'city' => 'Vanrhynsdorp'],
            ['id' => 90, 'province_id' => 9, 'city' => 'Genadendal'],
            ['id' => 91, 'province_id' => 9, 'city' => 'Rawsonville'],
            ['id' => 92, 'province_id' => 10, 'city' => 'Bulawayo'],
            ['id' => 93, 'province_id' => 11, 'city' => 'Harare'],
            ['id' => 94, 'province_id' => 11, 'city' => 'Chitungwiza'],
            ['id' => 95, 'province_id' => 12, 'city' => 'Mutare'],
            ['id' => 96, 'province_id' => 12, 'city' => 'Sakubva'],
            ['id' => 97, 'province_id' => 12, 'city' => 'Rusape'],
            ['id' => 98, 'province_id' => 12, 'city' => 'Chipinge'],
            ['id' => 99, 'province_id' => 12, 'city' => 'Buhera'],
            ['id' => 100, 'province_id' => 12, 'city' => 'Chimanimani'],
            ['id' => 101, 'province_id' => 12, 'city' => 'Nyanga'],
            ['id' => 102, 'province_id' => 13, 'city' => 'Bindura'],
            ['id' => 103, 'province_id' => 13, 'city' => 'Mukumbura'],
            ['id' => 104, 'province_id' => 13, 'city' => 'Mvurwi'],
            ['id' => 105, 'province_id' => 13, 'city' => 'Shamva'],
            ['id' => 106, 'province_id' => 13, 'city' => 'Mazoe'],
            ['id' => 107, 'province_id' => 13, 'city' => 'Mount Darwin'],
            ['id' => 108, 'province_id' => 13, 'city' => 'Guruve'],
            ['id' => 109, 'province_id' => 14, 'city' => 'Marondera'],
            ['id' => 110, 'province_id' => 14, 'city' => 'Ruwa'],
            ['id' => 111, 'province_id' => 14, 'city' => 'Murehwa'],
            ['id' => 112, 'province_id' => 14, 'city' => 'Mutoko'],
            ['id' => 113, 'province_id' => 14, 'city' => 'Chivhu'],
            ['id' => 114, 'province_id' => 14, 'city' => 'Goromonzi'],
            ['id' => 115, 'province_id' => 14, 'city' => 'Arcturus'],
            ['id' => 116, 'province_id' => 15, 'city' => 'Norton'],
            ['id' => 117, 'province_id' => 15, 'city' => 'Kadoma'],
            ['id' => 118, 'province_id' => 15, 'city' => 'Chegutu'],
            ['id' => 119, 'province_id' => 15, 'city' => 'Chinhoyi'],
            ['id' => 120, 'province_id' => 15, 'city' => 'Karoi'],
            ['id' => 121, 'province_id' => 15, 'city' => 'Kariba'],
            ['id' => 122, 'province_id' => 15, 'city' => 'Mhangura'],
            ['id' => 123, 'province_id' => 15, 'city' => 'Banket'],
            ['id' => 124, 'province_id' => 15, 'city' => 'Darwendale'],
            ['id' => 125, 'province_id' => 16, 'city' => 'Masvingo'],
            ['id' => 126, 'province_id' => 16, 'city' => 'Chiredzi'],
            ['id' => 127, 'province_id' => 16, 'city' => 'Zvishavane'],
            ['id' => 128, 'province_id' => 17, 'city' => 'Hwange'],
            ['id' => 129, 'province_id' => 17, 'city' => 'Victoria Falls'],
            ['id' => 130, 'province_id' => 17, 'city' => 'Lupane'],
            ['id' => 131, 'province_id' => 18, 'city' => 'Beitbridge'],
            ['id' => 132, 'province_id' => 18, 'city' => 'Kezi'],
            ['id' => 133, 'province_id' => 18, 'city' => 'Plumtree'],
            ['id' => 134, 'province_id' => 18, 'city' => 'Gwanda'],
            ['id' => 135, 'province_id' => 19, 'city' => 'Gweru'],
            ['id' => 136, 'province_id' => 19, 'city' => 'Kwekwe'],
            ['id' => 137, 'province_id' => 19, 'city' => 'Redcliff'],
            ['id' => 138, 'province_id' => 19, 'city' => 'Shurugwi'],
        ];

        foreach ($cities as $city) {
            City::query()->create($city);
        }
    }
}
