<?php

namespace Database\Seeders;

use App\Models\HostFirmConfig;
use Illuminate\Database\Seeder;

class HostFirmConfigSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $hostfirms = [
            ['hostFirm' => 'Baker Tilly', 'code' => '0001'],
            ['hostFirm' => 'BDO USA', 'code' => '0002'],
            ['hostFirm' => 'BDO Australia', 'code' => '0003'],
            ['hostFirm' => 'BDO UK LLP', 'code' => '0004'],
            ['hostFirm' => 'Bean', 'code' => '0005'],
            ['hostFirm' => 'Bentleys ', 'code' => '0006'],
            ['hostFirm' => 'Prager Metis', 'code' => '0007'],
            ['hostFirm' => 'BKD, LLP, BKD, LLP', 'code' => '0008'],
            ['hostFirm' => 'BPM', 'code' => '0009'],
            ['hostFirm' => 'BWB US', 'code' => '0010'],
            ['hostFirm' => 'Carpenter Box', 'code' => '0011'],
            ['hostFirm' => 'CBIZ', 'code' => '0012'],
            ['hostFirm' => 'Cherry Bekaert', 'code' => '0013'],
            ['hostFirm' => 'Cohen & CO', 'code' => '0014'],
            ['hostFirm' => 'CohnReznick', 'code' => '0015'],
            ['hostFirm' => 'Crowe UK', 'code' => '0016'],
            ['hostFirm' => 'Crowe US', 'code' => '0017'],
            ['hostFirm' => 'Deloitte Aus', 'code' => '0018'],
            ['hostFirm' => 'DFK Crosbie', 'code' => '0019'],
            ['hostFirm' => 'Forvis (DHG)', 'code' => '0020'],
            ['hostFirm' => 'Elliott Davis', 'code' => '0021'],
            ['hostFirm' => 'ESV Group', 'code' => '0022'],
            ['hostFirm' => 'Findex (Crowe)', 'code' => '0023'],
            ['hostFirm' => 'French Duncan', 'code' => '0024'],
            ['hostFirm' => 'GHJ', 'code' => '0025'],
            ['hostFirm' => 'Grant Thornton', 'code' => '0026'],
            ['hostFirm' => 'Lowe Lipman', 'code' => '0027'],
            ['hostFirm' => 'Menzies LLP', 'code' => '0028'],
            ['hostFirm' => 'S&W (Nexia)', 'code' => '0029'],
            ['hostFirm' => 'Pitcher Partners Melbourne', 'code' => '0030'],
            ['hostFirm' => 'PKF', 'code' => '0031'],
            ['hostFirm' => 'PWC', 'code' => '0032'],
            ['hostFirm' => 'Rehmann', 'code' => '0033'],
            ['hostFirm' => 'Rodefer Moss', 'code' => '0034'],
            ['hostFirm' => 'RSM US', 'code' => '0035'],
            ['hostFirm' => 'RSM NZ', 'code' => '0036'],
            ['hostFirm' => 'Smith & WIlliamson', 'code' => '0037'],
            ['hostFirm' => 'The MFA Companies ', 'code' => '0038'],
            ['hostFirm' => 'Withum', 'code' => '0039'],
            ['hostFirm' => 'Whitley Penn', 'code' => '0040'],
            ['hostFirm' => 'SAPRO (not yet placed)/Unassigned', 'code' => '0041'],
            ['hostFirm' => 'Kreischer Miller', 'code' => '0042'],
            ['hostFirm' => 'Moss Adams', 'code' => '0043'],
            ['hostFirm' => 'Hazlewoods', 'code' => '0044'],
            ['hostFirm' => 'BerryDunn', 'code' => '0045'],
            ['hostFirm' => 'SAPRO owned (Internal staff)', 'code' => '0046'],
            ['hostFirm' => 'UHY Hacker Young', 'code' => '0047'],
            ['hostFirm' => 'GRF CPAs & Advisors', 'code' => '0048'],
            ['hostFirm' => 'EY', 'code' => '0049'],
            ['hostFirm' => 'CapinCrouse', 'code' => '0050'],
            ['hostFirm' => 'Mazars UK', 'code' => '0051'],
            ['hostFirm' => 'Mitchell Titus', 'code' => '0052'],
            ['hostFirm' => 'Rubin Brown', 'code' => '0053'],
            ['hostFirm' => 'Councilor, Buchanan & Mitchell PC', 'code' => '0054'],
            ['hostFirm' => 'BDO Canada', 'code' => '0055'],
            ['hostFirm' => 'SJ CPA', 'code' => '0056'],
            ['hostFirm' => 'Hancock Askew', 'code' => '0057'],
            ['hostFirm' => 'HLB Man Judd', 'code' => '0058'],
            ['hostFirm' => 'Martin Aitken & Co', 'code' => '0059'],
            ['hostFirm' => 'Bloomberg', 'code' => '0060'],
            ['hostFirm' => 'Mengel Metzger Barr & Co', 'code' => '0061'],
            ['hostFirm' => 'Willet Advisors', 'code' => '0062'],
            ['hostFirm' => 'Aronson', 'code' => '0063'],
            ['hostFirm' => 'Poval', 'code' => '0064'],
            ['hostFirm' => 'Seiler', 'code' => '0065'],
            ['hostFirm' => 'HLB Gross Collins', 'code' => '0066'],
            ['hostFirm' => 'Brown Edwards', 'code' => '0067'],
            ['hostFirm' => 'Kruggel, Lawton & CO', 'code' => '0068'],
            ['hostFirm' => 'Maher Duessel', 'code' => '0069'],
            ['hostFirm' => 'Marcum US', 'code' => '0070'],
            ['hostFirm' => 'PKF Littlejohn UK', 'code' => '0071'],
            ['hostFirm' => 'Morgan Stanley', 'code' => '0072'],
            ['hostFirm' => 'PWC Luxembourg', 'code' => '0073'],
            ['hostFirm' => 'Smith Howard', 'code' => '0074'],
            ['hostFirm' => 'Armanino', 'code' => '0075'],
            ['hostFirm' => 'Bennett Thrasher', 'code' => '0076'],
            ['hostFirm' => 'EY Oceania', 'code' => '0077'],
            ['hostFirm' => 'Deloitte NZ', 'code' => '0078'],
            ['hostFirm' => 'Price Bailey', 'code' => '0079'],
            ['hostFirm' => 'GMA CPA', 'code' => '0080'],
            ['hostFirm' => 'Beever & Struther', 'code' => '0081'],
            ['hostFirm' => 'Deloitte Netherlands', 'code' => '0082'],
            ['hostFirm' => 'Fraizer Deeter', 'code' => '0083'],
            ['hostFirm' => 'Frank R', 'code' => '0084'],
            ['hostFirm' => 'Frost PLLC', 'code' => '0085'],
            ['hostFirm' => 'Morrows', 'code' => '0086'],
            ['hostFirm' => 'Nexia Perth', 'code' => '0087'],
            ['hostFirm' => 'Sasetti', 'code' => '0088'],
            ['hostFirm' => 'CBIZ NE', 'code' => '0089'],
            ['hostFirm' => 'CBIZ Philly', 'code' => '0090'],
            ['hostFirm' => 'CBIZ Phoenix', 'code' => '0091'],
            ['hostFirm' => 'CBIZ San Francisco', 'code' => '0092'],
            ['hostFirm' => 'CCK Strategies', 'code' => '0093'],
            ['hostFirm' => 'HLB Netherlands', 'code' => '0094'],
            ['hostFirm' => 'Miller Cooper', 'code' => '0095'],
            ['hostFirm' => 'PDR', 'code' => '0096'],
            ['hostFirm' => 'SC&H', 'code' => '0097'],
            ['hostFirm' => 'Janover LLC', 'code' => '0098'],
            ['hostFirm' => 'Warren Averette', 'code' => '0099'],
            ['hostFirm' => 'PKF NE', 'code' => '0100'],
            ['hostFirm' => 'RS&F Tax', 'code' => '0101'],
            ['hostFirm' => 'BMSS Tax', 'code' => '0102'],
            ['hostFirm' => 'CBIZ LA', 'code' => '0103'],
            ['hostFirm' => 'Hood - Tax', 'code' => '0104'],
            ['hostFirm' => 'Lumsden McCormick', 'code' => '0105'],
            ['hostFirm' => 'Fuller Landau', 'code' => '0106'],
            ['hostFirm' => 'PIMMS', 'code' => '0107'],
            ['hostFirm' => 'RSM Cayman', 'code' => '0108'],
            ['hostFirm' => 'AB Finwright', 'code' => '0109'],
            ['hostFirm' => 'CBIZ Kansas', 'code' => '0110'],
            ['hostFirm' => 'CBIZ NY', 'code' => '0111'],
            ['hostFirm' => 'CPA', 'code' => '0112'],
            ['hostFirm' => 'DKB', 'code' => '0113'],
            ['hostFirm' => 'HLB Blomer', 'code' => '0114'],
            ['hostFirm' => 'Wilken Guttenplan', 'code' => '0115'],
            ['hostFirm' => 'HLB Witlox van Boomen', 'code' => '0116'],
            ['hostFirm' => 'Pitcher Partners Brisbane', 'code' => '0117'],
            ['hostFirm' => 'Pitcher Partners Newcastle', 'code' => '0118'],
            ['hostFirm' => 'BDO Ireland', 'code' => '0119'],
            ['hostFirm' => 'Kaufman Rossin', 'code' => '0120'],
            ['hostFirm' => 'Crowe Soberman', 'code' => '0121'],
            ['hostFirm' => 'KPMG', 'code' => '0122'],
            ['hostFirm' => 'ABSA', 'code' => '0123'],
            ['hostFirm' => 'Webber Studios', 'code' => '0124'],
            ['hostFirm' => 'Weaver', 'code' => '0125'],
            ['hostFirm' => 'SVA', 'code' => '0126'],
            ['hostFirm' => 'Marcum Bookkeeping', 'code' => '0127'],
            ['hostFirm' => 'Mahoney Sabol', 'code' => '0128'],
            ['hostFirm' => 'BDO Netherlands', 'code' => '0129'],
            ['hostFirm' => 'Abdo', 'code' => '0130'],
            ['hostFirm' => 'EY Netherlands', 'code' => '0131'],
            ['hostFirm' => 'CBIZ Tax', 'code' => '0132'],
            ['hostFirm' => 'TWHC', 'code' => '0133'],
            ['hostFirm' => 'FAL', 'code' => '0134'],
            ['hostFirm' => 'Citrin Cooperman', 'code' => '0135'],
            ['hostFirm' => 'UHY London', 'code' => '0136'],
            ['hostFirm' => 'Edelstein CPA', 'code' => '0137'],
            ['hostFirm' => 'Sustainable DNA', 'code' => '0138'],
            ['hostFirm' => 'Pivot CPA', 'code' => '0139'],
            ['hostFirm' => 'Mercadien', 'code' => '0140'],
            ['hostFirm' => 'SST', 'code' => '0141'],
            ['hostFirm' => 'Lombardo Ayers', 'code' => '0142'],
            ['hostFirm' => 'WeCollabify', 'code' => '0143'],
            ['hostFirm' => 'Motor Happy', 'code' => '0144'],
            ['hostFirm' => 'Bentleys Adelaide', 'code' => '0145'],
            ['hostFirm' => 'Bentleys Brisbane', 'code' => '0146'],
            ['hostFirm' => 'Bentleys Sydney', 'code' => '0147'],
            ['hostFirm' => 'PKF MELBOURNE', 'code' => '0148'],
            ['hostFirm' => 'PKF SYDNEY', 'code' => '0149'],
            ['hostFirm' => 'Internal processes - AICPA', 'code' => '0150'],
            ['hostFirm' => 'BGM', 'code' => '0151'],
            ['hostFirm' => 'Nala Renewables', 'code' => '0152'],
            ['hostFirm' => 'CBIZ Memphis', 'code' => '0153'],
            ['hostFirm' => 'CBIZ Seattle', 'code' => '0154'],
            ['hostFirm' => 'CBIZ Boston', 'code' => '0155'],
            ['hostFirm' => 'CT Sports', 'code' => '0156'],
            ['hostFirm' => 'CBIZ Florida', 'code' => '0157'],
            ['hostFirm' => 'MGI', 'code' => '0158'],
            ['hostFirm' => 'Huddle Works', 'code' => '0159'],
            ['hostFirm' => 'Pitcher Partners Brisbane (JRB) - CAS', 'code' => '0160'],
            ['hostFirm' => 'Protea Holdings LLC', 'code' => '0161'],
            ['hostFirm' => 'RMB Securities', 'code' => '0162'],
            ['hostFirm' => 'Pitcher Partners Sydney', 'code' => '0163'],
            ['hostFirm' => 'Harambee', 'code' => '0164'],
            ['hostFirm' => 'Welch LLP', 'code' => '0165'],
            ['hostFirm' => 'Bernard Robinson & Co (BRC) ', 'code' => '0166'],

        ];

        foreach($hostfirms as $hostfirm){
            HostFirmConfig::query()->create($hostfirm);
        }
    }
}
