<?php

namespace Database\Seeders;

use App\Models\PriorExperienceRole;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PriorExperienceRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $priorExperiences = [
            ['priorExperienceRole' => 'Audit Consultant '],
            ['priorExperienceRole' => 'Audit Senior Associate'],
            ['priorExperienceRole' => 'Auditor-in Charge'],
            ['priorExperienceRole' => 'Experienced Associate'],
            ['priorExperienceRole' => 'Trainee Accountant'],
            ['priorExperienceRole' => 'Academic Clerk'],
            ['priorExperienceRole' => 'Accountant'],
            ['priorExperienceRole' => 'Accountant In-Charge'],
            ['priorExperienceRole' => 'Accounting Clerk'],
            ['priorExperienceRole' => 'Accounting Officer'],
            ['priorExperienceRole' => 'Accounts Clerk'],
            ['priorExperienceRole' => 'Acting Manager'],
            ['priorExperienceRole' => 'Advanced Associate'],
            ['priorExperienceRole' => 'Advanced Tax Analyst'],
            ['priorExperienceRole' => 'Advanced Tax Analyst II'],
            ['priorExperienceRole' => 'Advisory Senior Consultant'],
            ['priorExperienceRole' => 'Article Assistant'],
            ['priorExperienceRole' => 'Article Clerk'],
            ['priorExperienceRole' => 'Assistant Accountant'],
            ['priorExperienceRole' => 'Assistant Audit Manager'],
            ['priorExperienceRole' => 'Assistant Lecturer'],
            ['priorExperienceRole' => 'Assistant Manager'],
            ['priorExperienceRole' => 'Assistant Programme Accountant'],
            ['priorExperienceRole' => 'Assistant Tax Manager'],
            ['priorExperienceRole' => 'Associate'],
            ['priorExperienceRole' => 'Associate Accountant'],
            ['priorExperienceRole' => 'Associate Director'],
            ['priorExperienceRole' => 'Associate II/Senior'],
            ['priorExperienceRole' => 'Associate Manager'],
            ['priorExperienceRole' => 'Associate Resolution Planning Specialist'],
            ['priorExperienceRole' => 'Audit Assistant'],
            ['priorExperienceRole' => 'Audit Assistant Manager'],
            ['priorExperienceRole' => 'Audit Associate'],
            ['priorExperienceRole' => 'Audit Assurance Manager'],
            ['priorExperienceRole' => 'Audit Clerk'],
            ['priorExperienceRole' => 'Audit Consultant'],
            ['priorExperienceRole' => 'Audit Engagement partner'],
            ['priorExperienceRole' => 'Audit Executive'],
            ['priorExperienceRole' => 'Audit Intern'],
            ['priorExperienceRole' => 'Audit Manager'],
            ['priorExperienceRole' => 'Audit Semi Senior'],
            ['priorExperienceRole' => 'Audit Senior'],
            ['priorExperienceRole' => 'Audit Senior In-Charge'],
            ['priorExperienceRole' => 'Audit Supervisor'],
            ['priorExperienceRole' => 'Audit Trainee'],
            ['priorExperienceRole' => 'Auditing Lecturer'],
            ['priorExperienceRole' => 'Auditor'],
            ['priorExperienceRole' => 'Auditor in Charge'],
            ['priorExperienceRole' => 'Auditor Supervisor'],
            ['priorExperienceRole' => 'Bank Examiner'],
            ['priorExperienceRole' => 'Bookkeeper'],
            ['priorExperienceRole' => 'Business Analyst'],
            ['priorExperienceRole' => 'Chartered Accountant'],
            ['priorExperienceRole' => 'Chief Financial Officer'],
            ['priorExperienceRole' => 'Compliance Consultant'],
            ['priorExperienceRole' => 'Compliance Officer'],
            ['priorExperienceRole' => 'Compliance Specialist'],
            ['priorExperienceRole' => 'Consultant'],
            ['priorExperienceRole' => 'Consultant & Partner'],
            ['priorExperienceRole' => 'Deputy Manager'],
            ['priorExperienceRole' => 'Director'],
            ['priorExperienceRole' => 'Draft Financial Statement Assistant'],
            ['priorExperienceRole' => 'Engagement Auditor'],
            ['priorExperienceRole' => 'Exchange Control Analyst'],
            ['priorExperienceRole' => 'Executive'],
            ['priorExperienceRole' => 'External Associate Auditor'],
            ['priorExperienceRole' => 'External Audit Consultant'],
            ['priorExperienceRole' => 'External Audit Manager'],
            ['priorExperienceRole' => 'External Auditor'],
            ['priorExperienceRole' => 'Finance & Administration Manager'],
            ['priorExperienceRole' => 'Finance Assistant'],
            ['priorExperienceRole' => 'Finance Intern'],
            ['priorExperienceRole' => 'Finance Manager'],
            ['priorExperienceRole' => 'Finance Shared Services Manager'],
            ['priorExperienceRole' => 'Finance Trainee'],
            ['priorExperienceRole' => 'Financial Accountant'],
            ['priorExperienceRole' => 'Financial Accounting and Auditing Lecturer'],
            ['priorExperienceRole' => 'Financial Assistant'],
            ['priorExperienceRole' => 'Financial Controller'],
            ['priorExperienceRole' => 'Financial Manager'],
            ['priorExperienceRole' => 'Financial Monitoring Consultant'],
            ['priorExperienceRole' => 'Financial Reporting & Compliance Executive'],
            ['priorExperienceRole' => 'Financial Reporting Consultant'],
            ['priorExperienceRole' => 'Financial Statement Analyst'],
            ['priorExperienceRole' => 'Financial Statement Compiler'],
            ['priorExperienceRole' => 'General Manager'],
            ['priorExperienceRole' => 'Governance and Compliance Consultant (Probity Auditor)'],
            ['priorExperienceRole' => 'Group Finance Manager'],
            ['priorExperienceRole' => 'Group Financial Accountant'],
            ['priorExperienceRole' => 'Group Financial Controller'],
            ['priorExperienceRole' => 'Group Financial Manager'],
            ['priorExperienceRole' => 'HOD – Management Accounting'],
            ['priorExperienceRole' => 'Independent Contractor'],
            ['priorExperienceRole' => 'Intergroup Analyst'],
            ['priorExperienceRole' => 'Intermediate Trainee Accountant'],
            ['priorExperienceRole' => 'Internal Audit'],
            ['priorExperienceRole' => 'Internal Audit Supervisor'],
            ['priorExperienceRole' => 'Internal Auditor'],
            ['priorExperienceRole' => 'Investment Analyst'],
            ['priorExperienceRole' => 'Junior Accountant'],
            ['priorExperienceRole' => 'Junior Accounts Clerk'],
            ['priorExperienceRole' => 'Junior Auditor'],
            ['priorExperienceRole' => 'Junior CA'],
            ['priorExperienceRole' => 'Junior Consultant'],
            ['priorExperienceRole' => 'Junior External Auditor'],
            ['priorExperienceRole' => 'Junior Financial Controller'],
            ['priorExperienceRole' => 'Junior Manager'],
            ['priorExperienceRole' => 'Lead Internal Auditor'],
            ['priorExperienceRole' => 'Management Accountant'],
            ['priorExperienceRole' => 'Manager'],
            ['priorExperienceRole' => 'Managing Partner'],
            ['priorExperienceRole' => 'Mine Accountant'],
            ['priorExperienceRole' => 'Operational Specialist Financial Controller'],
            ['priorExperienceRole' => 'Payroll Administrator'],
            ['priorExperienceRole' => 'Practice Manager'],
            ['priorExperienceRole' => 'Practising Chartered Accountant'],
            ['priorExperienceRole' => 'Procurement and Supply Chain Consultant'],
            ['priorExperienceRole' => 'Project Accountant & Creditors Clerk'],
            ['priorExperienceRole' => 'Project Coordinator'],
            ['priorExperienceRole' => 'Project Manager'],
            ['priorExperienceRole' => 'Project Manager: Internal Audit'],
            ['priorExperienceRole' => 'Regional Accountant'],
            ['priorExperienceRole' => 'Resource Manager'],
            ['priorExperienceRole' => 'Retail Banking Manager'],
            ['priorExperienceRole' => 'Review Manager'],
            ['priorExperienceRole' => 'SAICA Article Clerk'],
            ['priorExperienceRole' => 'Semi-Senior'],
            ['priorExperienceRole' => 'Senior'],
            ['priorExperienceRole' => 'Senior Accountant'],
            ['priorExperienceRole' => 'Senior Advisory'],
            ['priorExperienceRole' => 'Senior Article Clerk'],
            ['priorExperienceRole' => 'Senior Associate'],
            ['priorExperienceRole' => 'Senior Associate 2'],
            ['priorExperienceRole' => 'Senior Assurance Associate'],
            ['priorExperienceRole' => 'Senior Audit'],
            ['priorExperienceRole' => 'Senior Audit Associate'],
            ['priorExperienceRole' => 'Senior Audit Clerk'],
            ['priorExperienceRole' => 'Senior Audit Consultant'],
            ['priorExperienceRole' => 'Senior Auditor'],
            ['priorExperienceRole' => 'Senior Consultant'],
            ['priorExperienceRole' => 'Senior Financial Consultant'],
            ['priorExperienceRole' => 'Senior Group Financial Accountant'],
            ['priorExperienceRole' => 'Senior In-Charge'],
            ['priorExperienceRole' => 'Senior Internal Auditor'],
            ['priorExperienceRole' => 'Senior Manager'],
            ['priorExperienceRole' => 'Senior Tax Analyst'],
            ['priorExperienceRole' => 'Senior Tax Associate'],
            ['priorExperienceRole' => 'Senior Tax Consultant'],
            ['priorExperienceRole' => 'Senior Trainee'],
            ['priorExperienceRole' => 'Senior Trainee Accountant'],
            ['priorExperienceRole' => 'SeniorAudit Consultant'],
            ['priorExperienceRole' => 'Senior-in Charge'],
            ['priorExperienceRole' => 'Service Delivery Centre Manager'],
            ['priorExperienceRole' => 'Service Resolution Specialist'],
            ['priorExperienceRole' => 'Supervisor'],
            ['priorExperienceRole' => 'TAS Advisors'],
            ['priorExperienceRole' => 'Tax Administrator'],
            ['priorExperienceRole' => 'Tax Analyst'],
            ['priorExperienceRole' => 'Tax Associate'],
            ['priorExperienceRole' => 'Tax Associate II'],
            ['priorExperienceRole' => 'Tax Consultant'],
            ['priorExperienceRole' => 'Tax Consultant II'],
            ['priorExperienceRole' => 'Tax Manager'],
            ['priorExperienceRole' => 'Tax Preparer'],
            ['priorExperienceRole' => 'Tax Reviewer'],
            ['priorExperienceRole' => 'Tax Senior'],
            ['priorExperienceRole' => 'Taxation & Accounting Lead'],
            ['priorExperienceRole' => 'Technical Assistant'],
            ['priorExperienceRole' => 'Trainee'],
            ['priorExperienceRole' => 'Trainee Associate'],
            ['priorExperienceRole' => 'Trainee Audit Clerk'],
            ['priorExperienceRole' => 'Trainee Auditor'],
            ['priorExperienceRole' => 'Treasury Analyst'],
            ['priorExperienceRole' => 'Trust Accountant'],
            ['priorExperienceRole' => 'University of Fort Hare'],
            ['priorExperienceRole' => 'US Tax Senior'],
            ['priorExperienceRole' => 'Value-add Delivery and Planning Functional Specialist'],
            ['priorExperienceRole' => 'Vat Auditor'],
        ];

        foreach ($priorExperiences as $experience) {
            PriorExperienceRole::query()->create($experience);
        }
    }
}
