<?php

namespace Database\Seeders;

use App\Models\SoftwareCategory;
use Illuminate\Database\Seeder;

class SoftwareCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            ['softwareCategory' => 'Checkpoint'],
            ['softwareCategory' => 'SAGE Fixed Assets '],
            ['softwareCategory' => 'Xero'],
            ['softwareCategory' => '1099 Pro '],
            ['softwareCategory' => 'Alteryx'],
            ['softwareCategory' => 'Amelio'],
            ['softwareCategory' => 'Findex APS'],
            ['softwareCategory' => 'Arbutus Analyzer'],
            ['softwareCategory' => 'AS2 Audit'],
            ['softwareCategory' => 'Audit Mate'],
            ['softwareCategory' => 'Audit Pro'],
            ['softwareCategory' => 'BDO Advantage'],
            ['softwareCategory' => 'BDO APT'],
            ['softwareCategory' => 'BDO APT Next Gen'],
            ['softwareCategory' => 'BDO Harmony'],
            ['softwareCategory' => 'Bloomberg'],
            ['softwareCategory' => 'BNA'],
            ['softwareCategory' => 'BNB'],
            ['softwareCategory' => 'Caseware'],
            ['softwareCategory' => 'CCH'],
            ['softwareCategory' => 'CCH Axcess'],
            ['softwareCategory' => 'CCH Engagement'],
            ['softwareCategory' => 'CCH Prosystem Fx '],
            ['softwareCategory' => 'CCS'],
            ['softwareCategory' => 'Checkpoint'],
            ['softwareCategory' => 'Citrix'],
            ['softwareCategory' => 'Connect'],
            ['softwareCategory' => 'Corptax'],
            ['softwareCategory' => 'Crowe Insight'],
            ['softwareCategory' => 'CSS'],
            ['softwareCategory' => 'Data Snipper'],
            ['softwareCategory' => 'Deloitte AS2'],
            ['softwareCategory' => 'Deloitte EMS'],
            ['softwareCategory' => 'DraftWorx'],
            ['softwareCategory' => 'Drake'],
            ['softwareCategory' => 'Exchange File Exchange Software'],
            ['softwareCategory' => 'EY Canvas'],
            ['softwareCategory' => 'Gfx'],
            ['softwareCategory' => 'Go System'],
            ['softwareCategory' => 'Google Suite'],
            ['softwareCategory' => 'Grant Thornton Voyager'],
            ['softwareCategory' => 'Halo'],
            ['softwareCategory' => 'HTML'],
            ['softwareCategory' => 'Hubble'],
            ['softwareCategory' => 'Hyperion Financial Management (HFM)  '],
            ['softwareCategory' => 'IDEA'],
            ['softwareCategory' => 'Ideagen Disclose'],
            ['softwareCategory' => 'iManage'],
            ['softwareCategory' => 'Inflo'],
            ['softwareCategory' => 'IPACS'],
            ['softwareCategory' => 'Javascript'],
            ['softwareCategory' => 'JD Edwards Software'],
            ['softwareCategory' => 'K1 Suite'],
            ['softwareCategory' => 'K-1G'],
            ['softwareCategory' => 'KPMG Clara'],
            ['softwareCategory' => 'KPMG eAudit'],
            ['softwareCategory' => 'Mazars REX'],
            ['softwareCategory' => 'Microsoft'],
            ['softwareCategory' => 'Microsoft Excel'],
            ['softwareCategory' => 'Microsoft Office'],
            ['softwareCategory' => 'Microsoft Outlook'],
            ['softwareCategory' => 'Microsoft PowerBI'],
            ['softwareCategory' => 'Microsoft PowerPoint'],
            ['softwareCategory' => 'Microsoft Teams'],
            ['softwareCategory' => 'Microsoft Word'],
            ['softwareCategory' => 'Monetary Unit - Sampling (MUS)'],
            ['softwareCategory' => 'MYOB'],
            ['softwareCategory' => 'Navision'],
            ['softwareCategory' => 'NetSuite'],
            ['softwareCategory' => 'Novision'],
            ['softwareCategory' => 'Oanda'],
            ['softwareCategory' => 'OneSource'],
            ['softwareCategory' => 'Oracle'],
            ['softwareCategory' => 'Oracle EBS'],
            ['softwareCategory' => 'Oracle PeopleSoft'],
            ['softwareCategory' => 'Ouickbooks'],
            ['softwareCategory' => 'Pastel'],
            ['softwareCategory' => 'PFX'],
            ['softwareCategory' => 'Power BI'],
            ['softwareCategory' => 'ProConnect Tax'],
            ['softwareCategory' => 'ProSeries'],
            ['softwareCategory' => 'ProSystems'],
            ['softwareCategory' => 'PWC Aura'],
            ['softwareCategory' => 'PWC Connect'],
            ['softwareCategory' => 'PWC Talent Link'],
            ['softwareCategory' => 'Python'],
            ['softwareCategory' => 'Qlikview'],
            ['softwareCategory' => 'Quickbooks'],
            ['softwareCategory' => 'SAGE'],
            ['softwareCategory' => 'Sage FAS '],
            ['softwareCategory' => 'SAGE Fixed Assets'],
            ['softwareCategory' => 'SAGE Pastel'],
            ['softwareCategory' => 'SAP'],
            ['softwareCategory' => 'SQL'],
            ['softwareCategory' => 'Superforms'],
            ['softwareCategory' => 'Suralink'],
            ['softwareCategory' => 'Syft Analytics'],
            ['softwareCategory' => 'SysPro'],
            ['softwareCategory' => 'T1'],
            ['softwareCategory' => 'Team Mate'],
            ['softwareCategory' => 'Thomson Reuters'],
            ['softwareCategory' => 'UltraTax'],
            ['softwareCategory' => 'Workday'],
            ['softwareCategory' => 'Zoom'],
        ];
        foreach ($categories as $category) {
            SoftwareCategory::query()->create($category);
        }
    }
}
